[tool.docstub.known_imports]
xarray = {import = "xarray"}
pandas = {import = "pandas"}
numpyro = {import = "numpyro"}
emcee = {import = "emcee"}
cmdstanpy = {import = "cmdstanpy"}
types = {import = "types"}

# Specify human-friendly aliases that can be used instead of Python-parsable
# annotations.
# TODO rename to qualname_alias or something
[tool.docstub.replace_doctypes]
hashable = "Hashable"
iterator = "Iterator"
module = "types.ModuleType"
labeller = "arviz_base.labels.Labeller"
Dataset = "xarray.Dataset"
DataTree = "xarray.DataTree"
# TODO: define a meta/pseudo type for DataTree-like
DataTree-like = "xarray.DataTree"
DataArray = "xarray.DataArray"
